from pathlib import Path

import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

from culvert_ai.field_reports import (
    _culvert_ids,
    _deduplicate_records,
    _normalize_route,
    _records_from_text,
    _report_date,
    append_field_report_candidates,
)
from culvert_ai.io import read_vector, write_vector


def test_report_date_parses_team_two_filename_formats():
    assert _report_date(Path("Team 2 field report - 5.21.26.pdf")) == "2026-05-21"
    assert _report_date(Path("Team 2 - Field Report 6_04_2026.docx.pdf")) == "2026-06-04"
    assert _report_date(Path("Team 2 Report updated Jun 1, 2026.pdf")) == "2026-06-01"
    assert _report_date(Path("Team 2 Field Report June 17, 2026.docx.pdf")) == "2026-06-17"
    assert _report_date(Path("18 JUNE 2026 TEAM 4 DAILY REPORT.pdf")) == "2026-06-18"


def test_records_from_text_handles_zero_width_pdf_spacing():
    text = "\u200bR-8\u200b NY-9G (CID: 149980) \u200b73.898 W\u200b \u200b42.056 N\u200b"

    records = _records_from_text(
        Path("Team 2 Field Report June 3, 2026.docx - Google Docs.pdf"),
        text,
    )

    assert len(records) == 1
    assert records[0].report_date == "2026-06-03"
    assert records[0].nysdot_region == "8"
    assert records[0].route == "NY9G"
    assert records[0].latitude == 42.056
    assert records[0].longitude == -73.898


def test_route_and_culvert_ids_are_normalized():
    assert _normalize_route("NY-9G") == "NY9G"
    assert _normalize_route("State Route 212") == "NY212"
    assert _normalize_route("Route 209") == "NY209"
    assert _normalize_route("US Hwy 9W") == "US9W"
    assert _culvert_ids("NY-9G (CID: 149980) SC150237 CID: Not Assigned") == [
        "CID149980",
        "SC150237",
        "CID-NOTASSIGNED",
    ]


def test_team_four_table_rows_keep_explicit_route_and_region():
    text = "1 8 28 Ulster County 42.036358 N 74.108094 W"

    records = _records_from_text(Path("17 JUNE 2026 TEAM 4 DAILY REPORT.pdf"), text)

    assert len(records) == 1
    assert records[0].report_date == "2026-06-17"
    assert records[0].nysdot_region == "8"
    assert records[0].route == "NY28"
    assert records[0].latitude == 42.036358
    assert records[0].longitude == -74.108094


def test_records_from_text_handles_split_line_coordinates_with_route_context():
    text = "\n".join(
        [
            "End Location: Route 209",
            "1. SC150598 Coordinates: 41.906449° N /",
            "74.084137° W",
            "Culvert SC150598: Located along Route 209.",
        ]
    )

    records = _records_from_text(
        Path("CS_CJ - Small Culvert Inventory Daily Field Report 07-09-2026.docx"),
        text,
    )

    assert len(records) == 1
    assert records[0].report_date == "2026-07-09"
    assert records[0].route == "NY209"
    assert records[0].culvert_id == "SC150598"
    assert records[0].latitude == 41.906449
    assert records[0].longitude == -74.084137


def test_records_from_text_normalizes_spaced_coordinate_digits():
    text = "8 NY 2 1 2 4 2. 089862 N 7 3. 940645 W"

    records = _records_from_text(
        Path("CS_CJ - Small Culvert Inventory Daily Field Report 06-24-2026.docx"),
        text,
    )

    assert len(records) == 1
    assert records[0].nysdot_region == "8"
    assert records[0].route == "NY212"
    assert records[0].latitude == 42.089862
    assert records[0].longitude == -73.940645


def test_records_from_text_normalizes_partially_spaced_route_digits():
    text = "8 NY2 14 42.101911N 74.307789W"

    records = _records_from_text(
        Path("CS_CJ - Small Culvert Inventory Daily Field Report 06-11-2026.docx"),
        text,
    )

    assert len(records) == 1
    assert records[0].nysdot_region == "8"
    assert records[0].route == "NY214"
    assert records[0].latitude == 42.101911
    assert records[0].longitude == -74.307789


def test_records_from_text_uses_standalone_spaced_route_line_for_next_coordinate():
    text = "\n".join(["8", "NY2 14", "42.101911N", "74.307789W"])

    records = _records_from_text(
        Path("CS_CJ - Small Culvert Inventory Daily Field Report 06-11-2026.docx"),
        text,
    )

    assert len(records) == 1
    assert records[0].nysdot_region == "8"
    assert records[0].route == "NY214"
    assert records[0].latitude == 42.101911
    assert records[0].longitude == -74.307789


def test_nearby_culvert_id_is_used_without_global_misalignment():
    text = "\n".join(
        [
            "R8 NY212 74.028352 W 42.073705 N",
            "1. [ID not generated by app] — Coordinates: 42.073705° N / 74.028352° W",
            "2. SC150332 — Condition Rating: Fair",
            "RM 212 — Coordinates: 42.069648° N / 74.041329° W",
        ]
    )

    records = _records_from_text(Path("18 JUNE 2026 TEAM 4 DAILY REPORT.pdf"), text)

    by_coordinate = {(record.latitude, record.longitude): record for record in records}
    assert by_coordinate[(42.073705, -74.028352)].culvert_id == ""
    assert by_coordinate[(42.069648, -74.041329)].culvert_id == "SC150332"


def test_deduplicate_prefers_identified_record_but_keeps_route():
    table = pd.DataFrame(
        [
            {
                "source_file": "team4.pdf",
                "report_date": "2026-06-18",
                "nysdot_region": "8",
                "route": "NY212",
                "latitude": 42.069648,
                "longitude": -74.041329,
                "raw_coordinate_text": "74.041329 W 42.069648 N",
                "culvert_id": "",
                "context_text": "R8 NY212 74.041329 W 42.069648 N",
                "label": "field_observed_culvert",
                "label_confidence": 0.85,
            },
            {
                "source_file": "team4.pdf",
                "report_date": "2026-06-18",
                "nysdot_region": "",
                "route": "",
                "latitude": 42.069648,
                "longitude": -74.041329,
                "raw_coordinate_text": "42.069648 N / 74.041329 W",
                "culvert_id": "SC150332",
                "context_text": "RM 212 — Coordinates: 42.069648 N / 74.041329 W",
                "label": "field_observed_culvert",
                "label_confidence": 0.85,
            },
        ]
    )

    deduped = _deduplicate_records(table, precision=6)

    assert len(deduped) == 1
    assert deduped.iloc[0]["culvert_id"] == "SC150332"
    assert deduped.iloc[0]["route"] == "NY212"


def test_append_field_report_candidates_continues_existing_field_ids(tmp_path):
    candidates = gpd.GeoDataFrame(
        [
            {"candidate_id": "cand_000001", "geometry": Point(0, 0)},
            {"candidate_id": "field_000012", "geometry": Point(1, 1)},
        ],
        geometry="geometry",
        crs="EPSG:4326",
    )
    field_points = gpd.GeoDataFrame(
        [
            {
                "route": "NY212",
                "culvert_id": "FC-1",
                "source_file": "field_observations.geojson",
                "geometry": Point(2, 2),
            }
        ],
        geometry="geometry",
        crs="EPSG:4326",
    )
    candidates_path = tmp_path / "candidates.gpkg"
    field_points_path = tmp_path / "field_points.gpkg"
    output_path = tmp_path / "combined.gpkg"
    write_vector(candidates, candidates_path)
    write_vector(field_points, field_points_path)

    append_field_report_candidates(candidates_path, field_points_path, output_path)

    combined = read_vector(output_path)
    assert combined["candidate_id"].tolist() == ["cand_000001", "field_000012", "field_000013"]
    assert pd.isna(combined.iloc[-1]["road_stream_distance_m"])


def test_append_field_report_candidates_preserves_negative_feedback_type(tmp_path):
    candidates = gpd.GeoDataFrame(
        [{"candidate_id": "cand_000001", "geometry": Point(0, 0)}],
        geometry="geometry",
        crs="EPSG:4326",
    )
    feedback = gpd.GeoDataFrame(
        [
            {
                "candidate_id": "old-candidate",
                "label": "no_culvert",
                "feedback_type": "inc",
                "observation_id": "obs-inc",
                "layout_source": "route_count_target_review",
                "source_file": "field_observations.geojson",
                "geometry": Point(1, 1),
            }
        ],
        geometry="geometry",
        crs="EPSG:4326",
    )
    candidates_path = tmp_path / "candidates.gpkg"
    feedback_path = tmp_path / "feedback.gpkg"
    output_path = tmp_path / "combined.gpkg"
    write_vector(candidates, candidates_path)
    write_vector(feedback, feedback_path)

    append_field_report_candidates(candidates_path, feedback_path, output_path)

    combined = read_vector(output_path)
    row = combined.iloc[-1]
    assert row["source"] == "field_observed_non_culvert"
    assert row["field_observation_label"] == "no_culvert"
    assert row["field_feedback_type"] == "inc"
