from pathlib import Path

import pandas as pd

from culvert_ai.field_reports import (
    _culvert_ids,
    _deduplicate_records,
    _normalize_route,
    _records_from_text,
    _report_date,
)


def test_report_date_parses_team_two_filename_formats():
    assert _report_date(Path("Team 2 field report - 5.21.26.pdf")) == "2026-05-21"
    assert _report_date(Path("Team 2 - Field Report 6_04_2026.docx.pdf")) == "2026-06-04"
    assert _report_date(Path("Team 2 Report updated Jun 1, 2026.pdf")) == "2026-06-01"
    assert _report_date(Path("Team 2 Field Report June 17, 2026.docx.pdf")) == "2026-06-17"
    assert _report_date(Path("18 JUNE 2026 TEAM 4 DAILY REPORT.pdf")) == "2026-06-18"


def test_records_from_text_handles_zero_width_pdf_spacing():
    text = "\u200bR-8\u200b NY-9G (CID: 149980) \u200b73.898 W\u200b \u200b42.056 N\u200b"

    records = _records_from_text(
        Path("Team 2 Field Report June 3, 2026.docx - Google Docs.pdf"),
        text,
    )

    assert len(records) == 1
    assert records[0].report_date == "2026-06-03"
    assert records[0].nysdot_region == "8"
    assert records[0].route == "NY9G"
    assert records[0].latitude == 42.056
    assert records[0].longitude == -73.898


def test_route_and_culvert_ids_are_normalized():
    assert _normalize_route("NY-9G") == "NY9G"
    assert _normalize_route("State Route 212") == "NY212"
    assert _culvert_ids("NY-9G (CID: 149980) SC150237 CID: Not Assigned") == [
        "CID149980",
        "SC150237",
        "CID-NOTASSIGNED",
    ]


def test_team_four_table_rows_keep_explicit_route_and_region():
    text = "1 8 28 Ulster County 42.036358 N 74.108094 W"

    records = _records_from_text(Path("17 JUNE 2026 TEAM 4 DAILY REPORT.pdf"), text)

    assert len(records) == 1
    assert records[0].report_date == "2026-06-17"
    assert records[0].nysdot_region == "8"
    assert records[0].route == "NY28"
    assert records[0].latitude == 42.036358
    assert records[0].longitude == -74.108094


def test_nearby_culvert_id_is_used_without_global_misalignment():
    text = "\n".join(
        [
            "R8 NY212 74.028352 W 42.073705 N",
            "1. [ID not generated by app] — Coordinates: 42.073705° N / 74.028352° W",
            "2. SC150332 — Condition Rating: Fair",
            "RM 212 — Coordinates: 42.069648° N / 74.041329° W",
        ]
    )

    records = _records_from_text(Path("18 JUNE 2026 TEAM 4 DAILY REPORT.pdf"), text)

    assert records[0].culvert_id == ""
    assert records[1].culvert_id == ""
    assert records[2].culvert_id == "SC150332"


def test_deduplicate_prefers_identified_record_but_keeps_route():
    table = pd.DataFrame(
        [
            {
                "source_file": "team4.pdf",
                "report_date": "2026-06-18",
                "nysdot_region": "8",
                "route": "NY212",
                "latitude": 42.069648,
                "longitude": -74.041329,
                "raw_coordinate_text": "74.041329 W 42.069648 N",
                "culvert_id": "",
                "context_text": "R8 NY212 74.041329 W 42.069648 N",
                "label": "field_observed_culvert",
                "label_confidence": 0.85,
            },
            {
                "source_file": "team4.pdf",
                "report_date": "2026-06-18",
                "nysdot_region": "",
                "route": "",
                "latitude": 42.069648,
                "longitude": -74.041329,
                "raw_coordinate_text": "42.069648 N / 74.041329 W",
                "culvert_id": "SC150332",
                "context_text": "RM 212 — Coordinates: 42.069648 N / 74.041329 W",
                "label": "field_observed_culvert",
                "label_confidence": 0.85,
            },
        ]
    )

    deduped = _deduplicate_records(table, precision=6)

    assert len(deduped) == 1
    assert deduped.iloc[0]["culvert_id"] == "SC150332"
    assert deduped.iloc[0]["route"] == "NY212"
